@startuml PlatformUM

'''Diagrama de clases de una aplicacion que brinda servicios de viajes'''

class User {
    - username: string
    - email: string
    - password: string
    - telephone: number
    - isAdmin: boolean
    - reservations: Reservation[]
    + logIn(): void
    + logOut(): void
    + registerUser(): void
    + validateUser(): void
    + showProfile(): void
    + showReservation(): void
}

class Trip {
    - origin: City
    - destination: City
    - date: Datetime
    - price: number
    - durationTravel: number
    - distance: number
    - totalPassengers: Passenger[]
    - totalSeats: number
    + checkSeats(): number
    + calculatePrice(): number
    + makeReservation(): void
}

class City {
    - name: string
    - state: string
}

class Reservation {
    - user: User
    - trip: Trip
    - date: Date
    - price: number
    - passengers: Passenger[]
}

class Passenger {
    - fullName: string
    - dateBirth: Date
    - nid: number
    - gender: string
    - reservation: Reservation
    - seatNumber: number
}

City -r-> Trip
Passenger --r--> Reservation
Passenger -u-> Trip
Reservation -u-> Trip
Reservation -u-> User

@enduml
